query getUser(
    $address: String! = "hi"
    $orderBy: [UsersOrderBy!]
) {
  user: allUsers(condition: { ethereumAddress: $address }, orderBy: $orderBy) {
    nodes {
      email
      id
      settings: userNotificationSettingByUserId {
        ...settingsField
      }
    }
  }
}

fragment settingsField on UserNotificationSetting {
  emailGiftReceiver
}