query getUser(
    $address: String!
    $orderBy: [UsersOrderBy!]
) {
  user: allUsers(condition: { ethereumAddress: $address }, orderBy: $orderBy) {
    nodes {
      email
      id
      settings: userNotificationSettingByUserId {
        emailGiftReceiver
      }
    }
  }
}
