query Films($firstFilms: Int! = 10, $firstStarships: Int! = 5) {
  allFilms(first: $firstFilms) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        title
        openingCrawl
        releaseDate
        starshipConnection(first: $firstStarships) {
          edges {
            node {
              name
              model
              starshipClass
            }
          }
        }
      }
    }
  }
}
